// Generated by https://quicktype.io

import { Organization } from './organization';
import { Repository } from './repository';
import { Sender } from './sender';

export interface Create {
  ref: string;
  ref_type: string;
  master_branch: string;
  description: string;
  pusher_type: string;
  repository: Repository;
  organization: Organization;
  sender: Sender;
}
