// Generated by https://quicktype.io

import { Sender } from './sender';

export interface Deployment {
  url: string;
  id: number;
  node_id: string;
  task: string;
  original_environment: string;
  environment: string;
  description: null;
  created_at: string;
  updated_at: string;
  statuses_url: string;
  repository_url: string;
  creator: Sender;
  sha: string;
  ref: string;
  payload: unknown;
  transient_environment: boolean;
  production_environment: boolean;
  performed_via_github_app: null;
}

export interface DeploymentStatusClass {
  url: string;
  id: number;
  node_id: string;
  state: string;
  creator: Sender;
  description: string;
  environment: string;
  target_url: string;
  created_at: string;
  updated_at: string;
  deployment_url: string;
  repository_url: string;
  environment_url: string;
  log_url: string;
  performed_via_github_app: null;
}
