// Generated by https://quicktype.io

import { Organization } from './organization';
import { Repository } from './repository';
import { Sender } from './sender';

export interface Label {
  action: string;
  label: LabelClass;
  repository: Repository;
  organization: Organization;
  sender: Sender;
}

export interface LabelClass {
  id: number;
  node_id: string;
  url: string;
  name: string;
  color: string;
  default: boolean;
  description: string;
}
