import { Organization } from './organization';
import { Repository } from './repository';
import { Sender } from './sender';

// Generated by https://quicktype.io

export interface Milestone {
  action: string;
  milestone: MilestoneClass;
  repository: Repository;
  organization: Organization;
  sender: Sender;
}

export interface MilestoneClass {
  url: string;
  html_url: string;
  labels_url: string;
  id: number;
  node_id: string;
  number: number;
  title: string;
  description: string;
  creator: Sender;
  open_issues: number;
  closed_issues: number;
  state: string;
  created_at: string;
  updated_at: string;
  due_on: null;
  closed_at: null;
}
