// Generated by https://quicktype.io

export interface Hook {
  type: string;
  id: number;
  name: string;
  active: boolean;
  events: string[];
  config: Config;
  updated_at: string;
  created_at: string;
  url: string;
  ping_url: string;
  deliveries_url: string;
}

export interface Config {
  content_type: string;
  insecure_ssl: string;
  url: string;
}
