// Generated by https://quicktype.io

import { Author } from './author';
import { Sender } from './sender';

export interface Branch {
  name: string;
  commit: TreeClass;
  protected: boolean;
}

export interface TreeClass {
  sha: string;
  url: string;
}

export interface StatusCommit {
  sha: string;
  node_id: string;
  commit: PurpleCommit;
  url: string;
  html_url: string;
  comments_url: string;
  author: Sender;
  committer: Sender;
  parents: Parent[];
}

export interface PurpleCommit {
  author: Author;
  committer: Author;
  message: string;
  tree: TreeClass;
  url: string;
  comment_count: number;
  verification: Verification;
}

export interface Verification {
  verified: boolean;
  reason: string;
  signature: null;
  payload: null;
}

export interface Parent {
  sha: string;
  url: string;
  html_url: string;
}
