// Generated by https://quicktype.io

import { Author } from './author';
import { Organization } from './organization';
import { Repository } from './repository';
import { Sender } from './sender';

export interface Status {
  id: number;
  sha: string;
  name: string;
  target_url: string;
  avatar_url: string;
  context: string;
  description: string;
  state: string;
  commit: StatusCommit;
  branches: Branch[];
  created_at: string;
  updated_at: string;
  repository: Repository;
  organization: Organization;
  sender: Sender;
}

export interface Branch {
  name: string;
  commit: TreeClass;
  protected: boolean;
}

export interface TreeClass {
  sha: string;
  url: string;
}

export interface StatusCommit {
  sha: string;
  node_id: string;
  commit: PurpleCommit;
  url: string;
  html_url: string;
  comments_url: string;
  author: Sender;
  committer: Sender;
  parents: Parent[];
}

export interface PurpleCommit {
  author: Author;
  committer: Author;
  message: string;
  tree: TreeClass;
  url: string;
  comment_count: number;
  verification: Verification;
}

export interface Verification {
  verified: boolean;
  reason: string;
  signature: null;
  payload: null;
}

export interface Parent {
  sha: string;
  url: string;
  html_url: string;
}
