// Generated by https://quicktype.io

import { HeadCommit } from './headCommit';
import { HeadRepository } from './headRepository';
import { Sender } from './sender';

export interface WorkflowRunClass {
  actor: Sender;
  artifacts_url: string;
  cancel_url: string;
  check_suite_id: number;
  check_suite_node_id: string;
  check_suite_url: string;
  conclusion: null | string;
  created_at: string;
  display_title: string;
  event: string;
  head_branch: string;
  head_commit: HeadCommit;
  head_repository: HeadRepository;
  head_sha: string;
  html_url: string;
  id: number;
  jobs_url: string;
  logs_url: string;
  name: string;
  node_id: string;
  path: string;
  previous_attempt_url: null;
  pull_requests: unknown[];
  referenced_workflows: unknown[];
  repository: HeadRepository;
  rerun_url: string;
  run_attempt: number;
  run_number: number;
  run_started_at: string;
  status: string;
  triggering_actor: Sender;
  updated_at: string;
  url: string;
  workflow_id: number;
  workflow_url: string;
}
