// Generated by https://quicktype.io

import { Organization } from './organization';
import { Repository } from './repository';
import { Sender } from './sender';
import { Step } from './step';

export interface WorkflowJob {
  action: string;
  workflow_job: WorkflowJobClass;
  repository: Repository;
  organization: Organization;
  sender: Sender;
}

export interface WorkflowJobClass {
  check_run_url: string;
  completed_at: null;
  conclusion: null;
  created_at: string;
  head_branch: string;
  head_sha: string;
  html_url: string;
  id: number;
  labels: string[];
  name: string;
  node_id: string;
  run_attempt: number;
  run_id: number;
  run_url: string;
  runner_group_id: number | null;
  runner_group_name: string | null;
  runner_id: number | null;
  runner_name: string | null;
  started_at: string;
  status: string;
  steps: Step[];
  url: string;
  workflow_name: string;
}
